### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by zrenx** [udesk/UdeskSDK-Android#31]
5.x_android_Q 
5.3.3

我只想说：越来越坑了

```
2021-12-16 21:08:17.248 I/udesksdk: v4Messages url =https://***.udesk.cn/udesk_im/sdk/v4/im/messages.json;  v4Messages  params =?signature=0B4C0CAE17AC8780BC425EB45D7D9E8F68764A34&language=zh&nonce=9837960583482&platform=android&mode=reconnected&sdk_token=staging_3&sdk_version=5.3.3&platform_name=android&app_id=c3931f3fa1f9b0ae&more_marking=ImSession#889013561&echostr=b01a1e23-f49c-4999-a1ec-c9ac72b35ee3&timestamp=1639660097247
2021-12-16 21:08:17.439 W/Choreographer: Frame time is 0.14503 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2021-12-16 21:08:17.530 I/udesksdk: v4Messages response_message ={"code":"1000","message":"success","more_marking":"ImSession#889013391","robot_session_associated_id":"","messages":[{"id":4189542921,"user_id":417821,"im_sub_session_id":912842901,"sender":"agent","status":"system","send_status":"","message_id":"SYS-20211216195820432-2a8ec22f","created_at":"2021-12-16T19:58:20.100+08:00","content":{"type":"rich","data":{"content":"<p>您好，请问有什么可以为您服务？</p>"},"push_type":"sys_welcome_msg"},"agent_id":417821,"agent_jid":"agent_417821_58381@im03.udesk.cn","agent_nick_name":"JUSTLUXE","agent_avatar":"","log_type":"","session_type":"agent","order":1639655900.04921},{"id":4189543531,"user_id":417821,"im_sub_session_id":912842901,"sender":"agent","status":"system","send_status":"","message_id":"21756d69-9ab5-4bc7-b259-ee2788cbfe8e","created_at":"2021-12-16T19:58:37.000+08:00","content":{"type":"offline_reassign","data":{"content":"此客户再次进线，此对话自动关闭"}},"agent_id":417821,"agent_jid":"agent_417821_58381@im03.udesk.cn","agent_nick_name":"JUSTLUXE","agent_avatar":"","log_type":"","session_type":"agent","order":1639655917.04531},{"id":"1639659102100000","customer_im_pre_form_id":318162981,"created_at":"2021-12-16T20:51:42.877+08:00","created_time":1639659102877.444,"updated_at":"2021-12-16T20:51:42.877+08:00","send_status":"arrive","content":{"data":{"content":"已付款订单，交易号：  211216618632"}},"content_raw":{"content":"已付款订单，交易号：  211216618632"},"now":"2021-12-16T21:08:17.486+08:00","agent_id":"","agent_nick_name":"","agent_avatar":"","log_type":"message","session_type":"pre_session","customer_id":3127125361,"sender":"customer","logId":"1639659102100000","message_id":"1639659102100000","order":1639659102.08}]}
2021-12-16 21:08:17.530 I/UdeskRequest: done
2021-12-16 21:08:17.531 I/xxxxx:  type = 44
2021-12-16 21:08:17.536 W/System.err: java.lang.NumberFormatException: For input string: "1639659102100000"
2021-12-16 21:08:17.536 W/System.err:     at java.lang.Integer.parseInt(Integer.java:618)
2021-12-16 21:08:17.536 W/System.err:     at java.lang.Integer.parseInt(Integer.java:650)
2021-12-16 21:08:17.536 W/System.err:     at udesk.core.utils.UdeskUtils.toInt(Unknown Source:0)
2021-12-16 21:08:17.536 W/System.err:     at udesk.core.utils.UdeskUtils.objectToInt(Unknown Source:67)
2021-12-16 21:08:17.536 W/System.err:     at udesk.core.model.LogBean.getLogId(Unknown Source:2)
2021-12-16 21:08:17.536 W/System.err:     at cn.udesk.UdeskUtil.buildAllMessage(UdeskUtil.java:1664)
2021-12-16 21:08:17.536 W/System.err:     at cn.udesk.activity.UdeskChatActivity$1.onChanged(UdeskChatActivity.java:1011)
2021-12-16 21:08:17.536 W/System.err:     at cn.udesk.activity.UdeskChatActivity$1.onChanged(UdeskChatActivity.java:481)
2021-12-16 21:08:17.537 W/System.err:     at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
2021-12-16 21:08:17.537 W/System.err:     at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
2021-12-16 21:08:17.537 W/System.err:     at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
2021-12-16 21:08:17.537 W/System.err:     at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
2021-12-16 21:08:17.537 W/System.err:     at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
2021-12-16 21:08:17.537 W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-12-16 21:08:17.537 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-12-16 21:08:17.537 W/System.err:     at android.os.Looper.loop(Looper.java:233)
2021-12-16 21:08:17.537 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8010)
2021-12-16 21:08:17.537 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-12-16 21:08:17.537 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
2021-12-16 21:08:17.537 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by huzhenhuastudy** [comment]
这个我们会尽快修复发版
