### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by smartAlienX** [udesk/UdeskSDK-Android#32]
出来修bug了

udesk_version = '5.3.3'

       FATAL EXCEPTION: Thread-14
Process: com.fommos, PID: 9071
java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.udesk.aac.livedata.RobotApiData.setSessionId(int)' on a null object reference
	at cn.udesk.aac.UdeskViewMode.setSessionId(Unknown Source:2)
	at cn.udesk.activity.UdeskChatActivity$1.onChanged(Unknown Source:1577)
	at cn.udesk.activity.UdeskChatActivity$1.onChanged(Unknown Source:2)
	at androidx.lifecycle.LiveData.considerNotify(Unknown Source:29)
	at androidx.lifecycle.LiveData.dispatchingValue(Unknown Source:44)
	at androidx.lifecycle.LiveData.setValue(Unknown Source:14)
	at androidx.lifecycle.y.setValue(Unknown Source:0)
	at androidx.lifecycle.LiveData$a.run(Unknown Source:18)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:7)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:4)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by huzhenhuastudy** [comment]
这个方便的话可以提个工单，描述下步骤或者录个屏，我们进一步排查下
